### ISSUE TITLE
Last several branches haven't worked with Vive?

### ISSUE THREAD

**Issue by Trichinosis** [Dryne11/SexyVR#1]
The newest builds don't seem to initialize OpenVR, it only opens on the desktop.  Revert to 0.3 release (~Jun 5) and it throws to the HMD correctly.

Is it maybe out-of-sync with the newest VRGIN.U46 builds?

Thanks!

**Comment by Dryne11** [comment]
Some DLL might be missing that don't get deployed into the plugin folder when compiling with the install goal. At least the LeapCSharp.NET3.5.dll and WindowsInput.dll from VRGIN. I will check later.

**Comment by Dryne11** [comment]
Building the solution with the install configuration copies all files now.
